//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetForMe.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BetForMeDBContainer : DbContext
    {
        public BetForMeDBContainer()
            : base("name=BetForMeDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<England_18_19> England_18_19 { get; set; }
        public virtual DbSet<Germany_18_19> Germany_18_19 { get; set; }
        public virtual DbSet<Spain_18_19> Spain_18_19 { get; set; }
    }
}
