//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetForMe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Germany_18_19
    {
        public string Div { get; set; }
        public string Date { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public Nullable<long> FTHG { get; set; }
        public Nullable<long> FTAG { get; set; }
        public string FTR { get; set; }
        public Nullable<long> HTHG { get; set; }
        public Nullable<long> HTAG { get; set; }
        public string HTR { get; set; }
        public Nullable<long> HS { get; set; }
        public Nullable<long> AS { get; set; }
        public Nullable<long> HST { get; set; }
        public Nullable<long> AST { get; set; }
        public Nullable<long> HF { get; set; }
        public Nullable<long> AF { get; set; }
        public Nullable<long> HC { get; set; }
        public Nullable<long> AC { get; set; }
        public Nullable<long> HY { get; set; }
        public Nullable<long> AY { get; set; }
        public Nullable<long> HR { get; set; }
        public Nullable<long> AR { get; set; }
        public Nullable<decimal> B365H { get; set; }
        public Nullable<decimal> B365D { get; set; }
        public Nullable<decimal> B365A { get; set; }
        public Nullable<decimal> BWH { get; set; }
        public Nullable<decimal> BWD { get; set; }
        public Nullable<decimal> BWA { get; set; }
        public Nullable<decimal> IWH { get; set; }
        public Nullable<decimal> IWD { get; set; }
        public Nullable<decimal> IWA { get; set; }
        public Nullable<decimal> PSH { get; set; }
        public Nullable<decimal> PSD { get; set; }
        public Nullable<decimal> PSA { get; set; }
        public Nullable<decimal> WHH { get; set; }
        public Nullable<decimal> WHD { get; set; }
        public Nullable<decimal> WHA { get; set; }
        public Nullable<decimal> VCH { get; set; }
        public Nullable<decimal> VCD { get; set; }
        public Nullable<decimal> VCA { get; set; }
        public Nullable<long> Bb1X2 { get; set; }
        public Nullable<decimal> BbMxH { get; set; }
        public Nullable<decimal> BbAvH { get; set; }
        public Nullable<decimal> BbMxD { get; set; }
        public Nullable<decimal> BbAvD { get; set; }
        public Nullable<decimal> BbMxA { get; set; }
        public Nullable<decimal> BbAvA { get; set; }
        public Nullable<long> BbOU { get; set; }
        public Nullable<decimal> BbMx_2_5 { get; set; }
        public Nullable<decimal> BbAv_2_5 { get; set; }
        public Nullable<decimal> BbMx_2_51 { get; set; }
        public Nullable<decimal> BbAv_2_51 { get; set; }
        public Nullable<long> BbAH { get; set; }
        public Nullable<decimal> BbAHh { get; set; }
        public Nullable<decimal> BbMxAHH { get; set; }
        public Nullable<decimal> BbAvAHH { get; set; }
        public Nullable<decimal> BbMxAHA { get; set; }
        public Nullable<decimal> BbAvAHA { get; set; }
        public Nullable<decimal> PSCH { get; set; }
        public Nullable<decimal> PSCD { get; set; }
        public Nullable<decimal> PSCA { get; set; }
        public long ID { get; set; }
    }
}
