//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetForMe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreseasonOdds
    {
        public long ID { get; set; }
        public string Championship { get; set; }
        public string Season { get; set; }
        public string TeamsList { get; set; }
    }
}
